# Configuration settings for the website

baseurl: "https://berdakh.github.io"
url: "https://berdakh.github.io"
googlescholar: "https://scholar.google.com/citations?user=YOUR_USER_ID"
bitbucket: "https://bitbucket.org/YOUR_REPO"